name: My First Github action pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Setup Python  
      uses: actions/setup-python@v6.1.0 
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Python Dependency Installation 
      uses: py-actions/py-dependency-install@v4
      with:
      run: |
        python -m pip install --upgrade pip
        pip install pytest    
    - name: Run Tests
      run: |
        python -m pytest addition.py    